services:
  django:
    depends_on:
      - database
    env_file:
      - ./confidential/.env
    container_name: django
    build:
      context: ./django
    user: "django"
    volumes:
      - backend:/usr/src/app
    expose:
      - "8000"
    ports:
      - 8000:8000
    networks:
      - intra_net

  database:
    container_name: pgsql
    build:
      context: ./pgsql
    restart: always
    shm_size: 128mb
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
      POSTGRES_PORT: ${DB_PORT}
    networks:
      - intra_net

  nginx:
    container_name: nginx
    restart: always
    depends_on:
      - django
    build:
      context: ./nginx
      args:
        - CERT_KEY=${CERT_KEY}
        - CERT_CRT=${CERT_CRT}
        - VITE_CLIENT_ID=${FT_ID} 
        - VITE_API_URI=${VITE_API_URI}
        - VITE_REDIRECT_URI=${VITE_REDIRECT_URI}
        - VITE_ROOM_WEBSOCKET_URI=${VITE_ROOM_WEBSOCKET_URI}
    env_file:
      - ./confidential/.env
    ports:
      - "443:443"
    expose:
      - "443"
    networks:
      - intra_net

  node:
    container_name: node
    restart: always
    build:
      context: ./node
    volumes:
      - frontend:/app
      - /app/node_modules
    ports:
      - 3100:3100
      - 24678:24678
    expose:
      - "3100"
    networks:
      - intra_net

  redis:
    container_name: redis
    restart: always
    build: ./redis
    expose:
      - "6379"
    networks:
      - intra_net

volumes:
  frontend:
    name: frontend
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/srcs/node/frontend
      o: bind
  backend:
    name: backend
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/srcs/django/backend
      o: bind
  database:
    name: database
    driver: local
    driver_opts:
      type: none
      device: ${DATA_PATH}
      o: bind

networks:
  intra_net:
    driver: bridge