services:
  django:
    container_name: django
    build:
      context: ./django
    user: "django"
    env_file:
      - .env
    volumes:
      - backend:/usr/src/app
    expose:
      - "8000"
    networks:
      - intra_net

  database:
    container_name: pgsql
    build:
      context: ./pgsql
    restart: always
    shm_size: 128mb
    # 데이터 경로 찾아서 수정
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "1234"
    networks:
      - intra_net

  nginx:
    container_name: nginx
    restart: always
    depends_on:
      - django
    build:
      context: ./nginx
      args:
        - CERT_KEY=${CERT_KEY}
        - CERT_CRT=${CERT_CRT}
    ports:
      - "443:443"
    expose:
      - "443"
    networks:
      - intra_net

  redis:
    container_name: redis
    restart: always
    build: ./redis
    expose:
      - "6379"
    networks:
      - intra_net

volumes:
  backend:
    name: backend
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/srcs/django/backend
      o: bind,rw
  database:
    name: database
    driver: local
    driver_opts:
      type: none
      device: ${DATA_PATH}
      o: bind,rw

networks:
  intra_net:
    driver: bridge