# specify the node base image with your desired version node:<version>

# 버전 어떤걸로 쓸 지 물어보고 반드시 수정 해야겠지? / slim 으로 패키지 다 빼고 서빙만 하는 식으로 간다.

# https://github.com/nodejs/docker-node/blob/main/README.md#how-to-use-this-image 문제있을 시 해당 링크 참고.
FROM node:16-slim
# replace this with your application's default port
EXPOSE 8888
WORKDIR /home/node/app
COPY ./frontend .

ENTRYPOINT [ "npm", "start" ]