FROM node:22

WORKDIR /app

COPY --chmod=755 ./tools/entrypoint.sh /
COPY --chmod=644 frontend/package.json ./
COPY --chmod=644 frontend/package-lock.json ./
RUN npm install
EXPOSE 3100
EXPOSE 24678

# USER node

ENTRYPOINT [ "/entrypoint.sh" ]

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
# CMD tail -f