FROM node:22

WORKDIR /home/node/app

COPY --chmod=755 ./tools/entrypoint.sh /
EXPOSE 3100

# USER node

ENTRYPOINT [ "/entrypoint.sh" ]

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
# CMD tail -f