#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  ALTER USER $POSTGRES_USER WITH NOSUPERUSER;
  ALTER USER $POSTGRES_USER WITH CREATEDB CREATEROLE;
  GRANT CONNECT ON DATABASE $POSTGRES_DB TO $POSTGRES_USER;
  -- 테이블 생성 권한 추가
  GRANT CREATE ON SCHEMA public TO $POSTGRES_USER;
EOSQL