FROM node:20 AS build-stage
WORKDIR /app
COPY frontend .

ARG VITE_API_URI \
	VITE_REDIRECTION_URI \
	VITE_CLIENT_ID \
	VITE_ROOM_WEBSOCKET_URI

RUN echo "VITE_API_URI=${VITE_API_URI}" >> .env && \
	echo "VITE_REDIRECTION_URI=${VITE_REDIRECTION_URI}" >> .env && \
	echo "VITE_CLIENT_ID=${VITE_CLIENT_ID}" >> .env && \
	echo "VITE_ROOM_WEBSOCKET_URI=${VITE_ROOM_WEBSOCKET_URI}" >> .env 

RUN npm install
RUN npm run build

# Production stage
FROM nginx:stable-alpine AS production-stage

COPY ./conf/nginx.conf /etc/nginx/nginx.conf
COPY ./conf/servers/https-server.conf /etc/nginx/servers/https-server.conf
COPY --from=build-stage /app/dist /usr/share/nginx/html/
COPY --from=build-stage /app/.env /usr/share/nginx/html/
ARG CERT_KEY \
	CERT_CRT

RUN	mkdir -p /etc/nginx/ssl && \
	echo -e "$CERT_KEY" > /etc/nginx/ssl/transcendance.key && \
	echo -e "$CERT_CRT" > /etc/nginx/ssl/transcendance.crt && \
	chmod 600 /etc/nginx/ssl/transcendance.key && \
	chmod 600 /etc/nginx/ssl/transcendance.crt && \
	chown nginx:nginx /etc/nginx/ssl/transcendance.key && \
	chown nginx:nginx /etc/nginx/ssl/transcendance.crt

EXPOSE 5173

CMD ["nginx", "-g", "daemon off;"]