FROM node:20 AS build-stage
WORKDIR /app
COPY frontend .
RUN npm install
RUN npm run build

# Production stage
FROM nginx:stable-alpine AS production-stage

COPY --from=build-stage /app/dist /usr/share/nginx/html/

COPY ./conf/nginx.conf /etc/nginx/nginx.conf
COPY ./conf/servers/https-server.conf /etc/nginx/servers/https-server.conf

ARG CERT_KEY \
	CERT_CRT

RUN	mkdir -p /etc/nginx/ssl && \
	echo -e "$CERT_KEY" > /etc/nginx/ssl/transcendance.key && \
	echo -e "$CERT_CRT" > /etc/nginx/ssl/transcendance.crt && \
	chmod 600 /etc/nginx/ssl/transcendance.key && \
	chmod 600 /etc/nginx/ssl/transcendance.crt && \
	chown nginx:nginx /etc/nginx/ssl/transcendance.key && \
	chown nginx:nginx /etc/nginx/ssl/transcendance.crt && \
	touch /usr/share/nginx/html/.env && \
	echo "VITE_API_URI=$VITE_API_URI" >> /usr/share/nginx/html/.env && \
	echo "VITE_REDIRECTION_URI=$VITE_REDIRECTION_URI" >> /usr/share/nginx/html/.env
	
EXPOSE 5173

CMD ["nginx", "-g", "daemon off;"]