# Production stage
FROM nginx:stable-alpine AS production-stage

COPY ./conf/nginx.conf /etc/nginx/nginx.conf
COPY ./conf/servers/https-server.conf /etc/nginx/servers/https-server.conf

ARG CERT_KEY \
	CERT_CRT

RUN	mkdir -p /etc/nginx/ssl && \
	echo -e "$CERT_KEY" > /etc/nginx/ssl/transcendance.key && \
	echo -e "$CERT_CRT" > /etc/nginx/ssl/transcendance.crt && \
	chmod 600 /etc/nginx/ssl/transcendance.key && \
	chmod 600 /etc/nginx/ssl/transcendance.crt && \
	chown nginx:nginx /etc/nginx/ssl/transcendance.key && \
	chown nginx:nginx /etc/nginx/ssl/transcendance.crt
	
EXPOSE 5173

CMD ["nginx", "-g", "daemon off;"]