# 일단 3.12 기준으로 잡았는데 BE 측에서 원하는 버전으로 수정해야함.
FROM python:3.12

RUN apt-get update \
	&& apt-get install -y --no-install-recommends \
		postgresql-client \
	&& rm -rf /var/lib/apt/lists/*
	
WORKDIR /usr/src/app
COPY ./backend .
RUN pip install -r requirements.txt && \
	groupadd -r django && useradd -r -g django django && \
	chown -R django:django /usr/src/app

EXPOSE 8000
USER django

ENTRYPOINT ["python3", "manage.py"]
CMD ["runserver", "0.0.0.0:8000"]