# 일단 3.12 기준으로 잡았는데 BE 측에서 원하는 버전으로 수정해야함.
FROM python:3.12

RUN apt-get update \
	&& apt-get install -y --no-install-recommends \
		postgresql-client \
	&& rm -rf /var/lib/apt/lists/*
	
WORKDIR /usr/src/app
COPY backend .
COPY ft_entrypoint.sh /ft_entrypoint.sh
RUN pip install -r requirements.txt && \
	groupadd -r django && useradd -r -g django django && \
	chmod 777 /ft_entrypoint.sh && \
	chown -R django:django /usr/src/app

EXPOSE 8000
USER django

ENTRYPOINT ["/ft_entrypoint.sh"]
CMD ["python3", "manage.py", "runserver", "0.0.0.0:8000"]

# ENTRYPOINT [ "/bin/bash" ]
# CMD ["tail", "-f", "/dev/null"]